#!/bin/bash

ln -s $HOME/www/riverside/wp-content/themes/kairos-riverside/plugins/shortcodes.php $HOME/www/riverside/wp-content/plugins/shortcodes.php
ln -s $HOME/www/riverside/wp-content/themes/kairos-riverside/plugins/gpphoto $HOME/www/riverside/wp-content/plugins/gpphoto
ln -s $HOME/www/riverside/wp-content/themes/kairos-riverside/plugins/gpevent $HOME/www/riverside/wp-content/plugins/gpevent

